import React, { useState } from 'react';
import { 
  ShieldAlert, 
  Clock, 
  MapPin, 
  CheckCircle2, 
  Send, 
  ChevronRight,
  TrendingUp,
  Flame,
  Truck,
  Activity,
  AlertTriangle,
  X,
  Radio,
  FileText,
  Target
} from 'lucide-react';
import type { AuthorityAlert } from '../../types';
import { RiskBadge } from '../common/RiskBadge';

interface AuthorityAlertsViewProps {
  alerts: AuthorityAlert[];
  city: string;
}

export const AuthorityAlertsView: React.FC<AuthorityAlertsViewProps> = ({ alerts, city }) => {
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [selectedSeverity, setSelectedSeverity] = useState<string>('all');
  const [selectedAlertForDetail, setSelectedAlertForDetail] = useState<AuthorityAlert | null>(null);
  const [actionedAlerts, setActionedAlerts] = useState<Record<string, string>>({});

  const filteredAlerts = alerts.filter(a => {
    const matchCategory = selectedCategory === 'all' || a.category === selectedCategory;
    const matchSeverity = selectedSeverity === 'all' || a.severity.toLowerCase() === selectedSeverity.toLowerCase();
    return matchCategory && matchSeverity;
  });

  const criticalAlerts = alerts.filter(a => a.severity === 'Critical');
  const highAlerts = alerts.filter(a => a.severity === 'High');

  const handleAction = (id: string, actionName: string = 'Dispatched') => {
    setActionedAlerts(prev => ({ ...prev, [id]: actionName }));
  };

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'pollution_spike':
        return <TrendingUp className="w-4 h-4 text-rose-400" />;
      case 'recurring_hotspot':
        return <Flame className="w-4 h-4 text-amber-400" />;
      case 'vehicle_cluster':
        return <Truck className="w-4 h-4 text-cyan-400" />;
      default:
        return <ShieldAlert className="w-4 h-4 text-emerald-400" />;
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2.5">
            <span className="p-2 rounded-xl bg-rose-500/10 text-rose-400 border border-rose-500/20">
              <ShieldAlert className="w-5 h-5" />
            </span>
            <div>
              <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
                Municipal Authority Action Dispatches
              </h2>
              <p className="text-xs text-slate-400 mt-0.5">
                Real-time incident response ledger generated by NIRVĀYU predictive dispersion and optical screening for {city}.
              </p>
            </div>
          </div>
        </div>

        {/* Status Counter Chips */}
        <div className="flex items-center gap-2.5 flex-wrap">
          <div className="px-3 py-1.5 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs font-semibold flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-rose-500 animate-ping" />
            <span>{criticalAlerts.length} Critical Immediate</span>
          </div>
          <div className="px-3 py-1.5 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-300 text-xs font-semibold flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-amber-400" />
            <span>{highAlerts.length} High Priority</span>
          </div>
          <div className="px-3 py-1.5 rounded-xl bg-slate-900 border border-slate-800 text-slate-300 text-xs font-semibold">
            <span>{alerts.length} Total Dispatches</span>
          </div>
        </div>
      </div>

      {/* PROMINENT HIGH-PRIORITY / CRITICAL ALERTS HERO BANNER */}
      {criticalAlerts.length > 0 && (
        <div className="p-5 rounded-2xl bg-gradient-to-r from-rose-950/40 via-slate-900/90 to-amber-950/30 border border-rose-500/40 shadow-xl shadow-rose-950/20 space-y-3.5">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="p-1 rounded bg-rose-500 text-slate-950 font-bold text-[10px] uppercase tracking-wider">
                URGENT MUNICIPAL ACTION REQUIRED
              </span>
              <span className="text-xs text-rose-300 font-medium">Active High-Priority Hotspot</span>
            </div>
            <span className="text-xs text-slate-400 font-mono">Incident #{criticalAlerts[0].id}</span>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 items-center">
            <div className="lg:col-span-8 space-y-1.5">
              <h3 className="text-base sm:text-lg font-bold text-white">
                {criticalAlerts[0].title}
              </h3>
              <p className="text-xs text-slate-300 leading-relaxed line-clamp-2">
                {criticalAlerts[0].description}
              </p>
              <div className="flex flex-wrap items-center gap-3 text-xs text-slate-400 pt-1">
                <span className="flex items-center gap-1 text-emerald-300 font-medium">
                  <MapPin className="w-3.5 h-3.5" />
                  {criticalAlerts[0].location}
                </span>
                <span>•</span>
                <span className="text-rose-400 font-bold">
                  Peak Projected: {criticalAlerts[0].predicted_aqi_peak} AQI ({criticalAlerts[0].horizon})
                </span>
                <span>•</span>
                <span className="text-cyan-400 font-semibold">
                  Probability: {(Number(criticalAlerts[0].probability) * 100).toFixed(0)}%
                </span>
              </div>
            </div>

            <div className="lg:col-span-4 flex flex-col sm:flex-row lg:flex-col gap-2 justify-end">
              <button
                onClick={() => setSelectedAlertForDetail(criticalAlerts[0])}
                className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-white text-xs font-semibold flex items-center justify-center gap-2 border border-slate-700 transition-all cursor-pointer"
              >
                <FileText className="w-3.5 h-3.5" />
                <span>View Full Evidence & Supporting Data</span>
              </button>
              
              {actionedAlerts[criticalAlerts[0].id] ? (
                <div className="px-4 py-2 rounded-xl bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 text-xs font-semibold flex items-center justify-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  <span>Protocol Dispatched</span>
                </div>
              ) : (
                <button
                  onClick={() => handleAction(criticalAlerts[0].id, 'Dispatched Anti-Smog Protocol')}
                  className="px-4 py-2.5 rounded-xl bg-rose-600 hover:bg-rose-500 text-white text-xs font-bold flex items-center justify-center gap-2 shadow-lg shadow-rose-900/40 transition-all cursor-pointer"
                >
                  <Send className="w-3.5 h-3.5" />
                  <span>Execute Emergency Anti-Smog Dispatch</span>
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Filter Toolbar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-900/60 p-3 rounded-2xl border border-slate-800">
        {/* Category Tabs */}
        <div className="flex items-center gap-1.5 flex-wrap">
          {[
            { id: 'all', label: 'All Dispatches' },
            { id: 'pollution_spike', label: 'Pollution Spikes' },
            { id: 'recurring_hotspot', label: 'Recurring Hotspots' },
            { id: 'vehicle_cluster', label: 'Vehicle Clusters' },
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setSelectedCategory(tab.id)}
              className={`px-3 py-1.5 rounded-xl text-xs font-medium transition-all ${
                selectedCategory === tab.id
                  ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 shadow-sm'
                  : 'bg-slate-900 border border-slate-800/80 text-slate-400 hover:text-slate-200'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Severity Selector */}
        <div className="flex items-center gap-2 text-xs">
          <span className="text-slate-400 font-medium">Severity:</span>
          <select
            value={selectedSeverity}
            onChange={(e) => setSelectedSeverity(e.target.value)}
            className="bg-slate-900 border border-slate-700 rounded-xl px-2.5 py-1.5 text-xs text-white focus:outline-none focus:border-emerald-500"
          >
            <option value="all">All Severities</option>
            <option value="critical">Critical</option>
            <option value="high">High</option>
            <option value="medium-high">Medium-High</option>
          </select>
        </div>
      </div>

      {/* Dispatches List */}
      <div className="space-y-4">
        {filteredAlerts.map((alert) => {
          const actionStatus = actionedAlerts[alert.id];
          return (
            <div
              key={alert.id}
              className={`glass-panel p-5 sm:p-6 rounded-2xl border transition-all ${
                alert.severity === 'Critical'
                  ? 'border-rose-500/30 bg-slate-900/80 hover:border-rose-500/50'
                  : 'border-slate-800 bg-slate-900/50 hover:border-slate-700'
              }`}
            >
              {/* Top Row: Category, Time, Probability, Peak AQI */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800/80 pb-4">
                <div className="flex items-center gap-2.5 flex-wrap">
                  <RiskBadge level={alert.severity} size="md" />
                  
                  <span className="text-xs font-semibold uppercase tracking-wider text-slate-300 bg-slate-800 px-2.5 py-1 rounded-lg flex items-center gap-1.5">
                    {getCategoryIcon(alert.category)}
                    {alert.category.replace('_', ' ')}
                  </span>

                  <span className="text-xs text-slate-400 flex items-center gap-1">
                    <Clock className="w-3.5 h-3.5" />
                    {alert.timestamp}
                  </span>

                  <span className="text-xs text-cyan-400 font-medium px-2 py-0.5 rounded bg-cyan-500/10 border border-cyan-500/20">
                    {(Number(alert.probability) * 100).toFixed(0)}% Probability
                  </span>
                </div>

                <div className="flex items-center gap-3">
                  <div className="text-right">
                    <span className="text-[10px] uppercase font-bold text-slate-400 block">Peak Predicted</span>
                    <span className="text-sm font-black text-rose-400 font-mono">
                      {alert.predicted_aqi_peak} AQI
                    </span>
                  </div>
                  <button
                    onClick={() => setSelectedAlertForDetail(alert)}
                    className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium flex items-center gap-1 border border-slate-700 transition-all cursor-pointer"
                  >
                    <span>Inspect Detail</span>
                    <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
                  </button>
                </div>
              </div>

              {/* Middle Row: Title, Location & Description */}
              <div className="py-4 space-y-3">
                <div>
                  <h3 className="text-base font-bold text-white flex items-center gap-2">
                    {alert.title}
                  </h3>
                  <div className="flex items-center gap-1.5 text-xs text-emerald-400/90 mt-1 font-medium">
                    <MapPin className="w-3.5 h-3.5" />
                    <span>{alert.location}</span>
                    <span className="text-slate-500">• Horizon: {alert.horizon}</span>
                  </div>
                </div>

                <p className="text-xs text-slate-300 leading-relaxed">
                  {alert.description}
                </p>

                {/* Factors checklist preview */}
                <div className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800 space-y-1.5">
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-slate-400 block">
                    Observed Trigger Factors:
                  </span>
                  <ul className="grid grid-cols-1 md:grid-cols-2 gap-1.5">
                    {alert.factors.map((factor, fIdx) => (
                      <li key={fIdx} className="text-xs text-slate-300 flex items-start gap-2">
                        <span className="text-rose-400 mt-0.5">•</span>
                        <span>{factor}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Bottom Row: Recommended Actions & Dispatch Button */}
              <div className="pt-4 border-t border-slate-800/80 flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div className="space-y-1.5 flex-1">
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-emerald-400 flex items-center gap-1">
                    <CheckCircle2 className="w-3.5 h-3.5" /> Recommended Municipal Protocols:
                  </span>
                  <div className="space-y-1">
                    {alert.recommended_actions.slice(0, 2).map((act, actIdx) => (
                      <div key={actIdx} className="text-xs text-slate-300 flex items-start gap-2">
                        <ChevronRight className="w-3 h-3 text-slate-500 shrink-0 mt-0.5" />
                        <span>{act}</span>
                      </div>
                    ))}
                  </div>
                </div>

                <div className="self-end md:self-center shrink-0 flex items-center gap-2">
                  {actionStatus ? (
                    <div className="px-4 py-2 rounded-xl bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 text-xs font-semibold flex items-center gap-1.5">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                      <span>{actionStatus}</span>
                    </div>
                  ) : (
                    <button
                      onClick={() => handleAction(alert.id, 'Action Protocol Dispatched')}
                      className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white text-xs font-semibold flex items-center gap-2 shadow-lg shadow-emerald-950/40 transition-all cursor-pointer"
                    >
                      <Send className="w-3.5 h-3.5" />
                      <span>Dispatch Response Protocol</span>
                    </button>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* ALERT DETAIL PANEL MODAL / DRAWER */}
      {selectedAlertForDetail && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-200">
          <div className="glass-panel-glow bg-slate-900 border border-slate-700 w-full max-w-3xl rounded-3xl overflow-hidden shadow-2xl space-y-0 max-h-[90vh] flex flex-col">
            {/* Modal Header */}
            <div className="p-6 border-b border-slate-800 flex items-start justify-between gap-4 bg-slate-950/50">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <RiskBadge level={selectedAlertForDetail.severity} size="md" />
                  <span className="text-xs font-semibold uppercase tracking-wider text-slate-400 bg-slate-800 px-2 py-0.5 rounded">
                    {selectedAlertForDetail.category.replace('_', ' ')}
                  </span>
                  <span className="text-xs text-slate-400">• ID: {selectedAlertForDetail.id}</span>
                </div>
                <h3 className="text-lg sm:text-xl font-bold text-white">
                  {selectedAlertForDetail.title}
                </h3>
                <div className="flex items-center gap-1.5 text-xs text-emerald-400">
                  <MapPin className="w-3.5 h-3.5" />
                  <span>{selectedAlertForDetail.location}</span>
                </div>
              </div>

              <button
                onClick={() => setSelectedAlertForDetail(null)}
                className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-all cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Body */}
            <div className="p-6 overflow-y-auto space-y-6 flex-1 text-xs">
              {/* 1. Why the alert was generated */}
              <div className="space-y-2 p-4 rounded-2xl bg-slate-950/70 border border-slate-800">
                <div className="flex items-center gap-2 text-rose-400 font-bold uppercase tracking-wider text-[11px]">
                  <AlertTriangle className="w-4 h-4" />
                  <span>Why This Alert Was Generated</span>
                </div>
                <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
                  {selectedAlertForDetail.why_generated}
                </p>
              </div>

              {/* 2. Supporting Data Telemetry Grid */}
              <div className="space-y-2.5">
                <div className="flex items-center gap-2 text-cyan-400 font-bold uppercase tracking-wider text-[11px]">
                  <Activity className="w-4 h-4" />
                  <span>Supporting Telemetry & Sensor Evidence</span>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800">
                    <span className="text-[10px] text-slate-400 block">Baseline AQI</span>
                    <span className="text-sm font-bold text-white">{selectedAlertForDetail.supporting_data?.baseline_aqi || 164} AQI</span>
                  </div>
                  <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800">
                    <span className="text-[10px] text-slate-400 block">Projected Peak</span>
                    <span className="text-sm font-bold text-rose-400">{selectedAlertForDetail.supporting_data?.predicted_peak_aqi || selectedAlertForDetail.predicted_aqi_peak} AQI</span>
                  </div>
                  <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800">
                    <span className="text-[10px] text-slate-400 block">Traffic Congestion</span>
                    <span className="text-sm font-bold text-cyan-300">{selectedAlertForDetail.supporting_data?.traffic_density || '88% High'}</span>
                  </div>
                  <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800">
                    <span className="text-[10px] text-slate-400 block">Wind Velocity</span>
                    <span className="text-sm font-bold text-teal-300">{selectedAlertForDetail.supporting_data?.wind_speed || '4.2 km/h'}</span>
                  </div>
                  <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800">
                    <span className="text-[10px] text-slate-400 block">Active Citizen Flags</span>
                    <span className="text-sm font-bold text-amber-300">{selectedAlertForDetail.supporting_data?.citizen_flags_count || 14} Reports</span>
                  </div>
                  <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800">
                    <span className="text-[10px] text-slate-400 block">Action Lead Time</span>
                    <span className="text-sm font-bold text-emerald-300">{selectedAlertForDetail.supporting_data?.lead_time_minutes || 35} Minutes</span>
                  </div>
                  <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 col-span-2">
                    <span className="text-[10px] text-slate-400 block">Fleet Category Mix</span>
                    <span className="text-sm font-bold text-slate-200">{selectedAlertForDetail.supporting_data?.heavy_vehicle_share || 'Heavy Logistics Freight'}</span>
                  </div>
                </div>
              </div>

              {/* 3. Recommended Intervention */}
              <div className="space-y-2 p-4 rounded-2xl bg-emerald-950/20 border border-emerald-500/30">
                <div className="flex items-center gap-2 text-emerald-400 font-bold uppercase tracking-wider text-[11px]">
                  <Radio className="w-4 h-4" />
                  <span>Recommended Municipal Intervention</span>
                </div>
                <p className="text-xs sm:text-sm text-slate-200 leading-relaxed font-medium">
                  {selectedAlertForDetail.recommended_intervention}
                </p>

                <div className="pt-2 space-y-1.5 border-t border-emerald-500/20">
                  <span className="text-[10px] font-bold text-slate-400 uppercase">Action Checklist:</span>
                  {selectedAlertForDetail.recommended_actions.map((act, i) => (
                    <div key={i} className="flex items-center gap-2 text-xs text-slate-300">
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                      <span>{act}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* 4. Expected Impact */}
              <div className="space-y-2 p-4 rounded-2xl bg-cyan-950/20 border border-cyan-500/30">
                <div className="flex items-center gap-2 text-cyan-400 font-bold uppercase tracking-wider text-[11px]">
                  <Target className="w-4 h-4" />
                  <span>Expected Environmental & Health Impact</span>
                </div>
                <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
                  {selectedAlertForDetail.expected_impact}
                </p>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="p-5 border-t border-slate-800 bg-slate-950/80 flex items-center justify-between gap-3">
              <button
                onClick={() => setSelectedAlertForDetail(null)}
                className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold transition-all cursor-pointer"
              >
                Close Panel
              </button>

              <button
                onClick={() => {
                  handleAction(selectedAlertForDetail.id, 'Municipal Protocol Dispatched');
                  setSelectedAlertForDetail(null);
                }}
                className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white text-xs font-bold flex items-center gap-2 shadow-lg shadow-emerald-950/50 transition-all cursor-pointer"
              >
                <Send className="w-3.5 h-3.5" />
                <span>Confirm & Authorize Dispatch</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
