from fastapi import APIRouter, Query
from pydantic import BaseModel, Field
from typing import List, Optional
from ..services.forecast_service import ForecastService

router = APIRouter(prefix="/api/forecast", tags=["AQI Forecast"])

class ForecastPredictionItem(BaseModel):
    horizon_minutes: int
    predicted_aqi: int
    confidence: float
    delta_from_baseline: int

class ContributingFactorItem(BaseModel):
    factor: str
    impact_pct: int
    direction: str

class GeminiReasoningPayload(BaseModel):
    overall_pollution_risk: str
    main_contributing_factors: List[str]
    plain_language_explanation: str
    recommended_authority_actions: List[str]
    confidence_interpretation: str
    source: Optional[str] = "Gemini Reasoning Engine"

class ForecastPayload(BaseModel):
    city: str
    current_aqi: int
    traffic_density: float
    wind_speed: float
    temperature: float
    heavy_vehicle_ratio: float
    forecast_timestamp: str
    numerical_prediction_source: str = "Scikit-Learn ML Model"
    reasoning_source: str = "Gemini Reasoning Engine"
    predictions: List[ForecastPredictionItem]
    confidence_overall: float
    contributing_factors: List[ContributingFactorItem]
    gemini_reasoning: GeminiReasoningPayload

class ForecastResponse(BaseModel):
    status: str = "success"
    city: str
    data: ForecastPayload

@router.get("", response_model=ForecastResponse)
def get_forecast(
    city: str = Query(default="Hyderabad", description="Target city for AQI forecast"),
    current_aqi: int = Query(default=164, ge=0, le=500, description="Current baseline AQI"),
    traffic_density: float = Query(default=0.85, ge=0.0, le=1.0, description="Normalized traffic congestion density index"),
    wind_speed: float = Query(default=5.2, ge=0.0, description="Wind speed in km/h"),
    temperature: float = Query(default=31.5, description="Ambient temperature in °C"),
    heavy_vehicle_ratio: float = Query(default=0.38, ge=0.0, le=1.0, description="Heavy commercial vehicle fleet ratio")
):
    """
    AQI Short-Term Forecasting Pipeline:
    - Numerical predictions computed via Scikit-Learn dispersion regression model.
    - Risk evaluation and plain-language interpretation generated by Gemini.
    """
    forecast_data = ForecastService.generate_forecast(
        city=city,
        current_aqi=current_aqi,
        traffic_density=traffic_density,
        wind_speed=wind_speed,
        temperature=temperature,
        heavy_vehicle_ratio=heavy_vehicle_ratio
    )
    return {
        "status": "success",
        "city": city,
        "data": forecast_data
    }
